# https://taskfile.dev

version: "3"

vars:
  DEBUG: #debug
# Define $DEBUG to get detailed logs from Terraform

tasks:
  setup:
    desc: configures your tfvars file
    summary: |
      Generates a .tfvars file for you to complete.
    cmds: 
      - "cp terraform.tfvars.example terraform.tfvars"
      - echo "Generated a template terraform.tfvars for you. Fill this in!"
    sources:
      - terraform.tfvars.example
    generates:
      - terraform.tfvars
    silent: true

  init:
    desc: Init your Terraform env
    cmds:
      - TF_LOG={{.DEBUG}} terraform init

  plan:
    desc: Create a Terraform plan
    cmds:
      - task: init
      - TF_LOG={{.DEBUG}} terraform plan -out=my_plan
    silent: true

  apply:
    desc: Apply a Terraform plan
    cmds:
      - task: init
      - task: plan
      - TF_LOG={{.DEBUG}} terraform apply my_plan

  destroy:
    desc: Destroy your Terraformed world
    cmds:
      - terraform destroy

  login:
    desc: Log in to your faasd appliance
    cmds:
      - ssh ubuntu@{{.IP}}
    vars:
      IP:
        sh: terraform output public_ip